apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config-2022
  namespace: argo-cd
spec:
  project: default
  source: 
    repoURL: https://github.com/bojann97/terraform-test.git
    targetRevision: HEAD
    path: deployment.tf
  destination:
    server: https://kubernetes.default.svc
    namespace: breweries
  syncPolicy:
    syncOptions:
      - CreateNamespaace = true
    automated:
      selfHeal: true
      prune: true
